CREATE TABLE RFM(CUSTOMERID INT,LASTINVOICEDATE DATETIME,
RECENCY INT,FREQUENCY INT,MONETARY FLOAT,
RECENCY_SCALE INT,FREQUENCY_SCALE INT,MONETARY_SCALE INT,
RF VARCHAR(10),SEGMENT VARCHAR(50))


TRUNCATE TABLE RFM


INSERT INTO RFM (CUSTOMERID)
SELECT DISTINCT CUSTOMERID FROM ONLINERETAIL_2009 WHERE CustomerID IS NOT NULL

UPDATE RFM SET LASTINVOICEDATE=
(SELECT MAX(InvoiceDate) FROM ONLINERETAIL_2009 WHERE CustomerID=RFM.CUSTOMERID)

UPDATE RFM SET RECENCY=DATEDIFF(DAY,LASTINVOICEDATE,'2010-12-31 23:59:59')


UPDATE RFM SET FREQUENCY=
(SELECT count(DISTINCT Invoice) FROM ONLINERETAIL_2009 WHERE CustomerID=RFM.CUSTOMERID)


UPDATE RFM SET MONETARY=
(SELECT SUM(Quantity*Price) FROM ONLINERETAIL_2009 WHERE CustomerID=RFM.CUSTOMERID)

UPDATE RFM SET RECENCY_SCALE=
(SELECT SCALE FROM
(
SELECT *,
NTILE(5) OVER(
ORDER BY RECENCY DESC) SCALE
FROM RFM
) T WHERE CUSTOMERID=RFM.CUSTOMERID)

UPDATE RFM SET FREQUENCY_SCALE=
(SELECT SCALE FROM
(
SELECT *,
NTILE(5) OVER(
ORDER BY FREQUENCY) SCALE
FROM RFM
) T WHERE CUSTOMERID=RFM.CUSTOMERID)

UPDATE RFM SET MONETARY_SCALE=
(SELECT SCALE FROM
(
SELECT *,
NTILE(5) OVER(
ORDER BY MONETARY_SCALE) SCALE
FROM RFM
) T WHERE CUSTOMERID=RFM.CUSTOMERID)

UPDATE RFM SET RF=CONVERT(VARCHAR,RECENCY_SCALE)+CONVERT(VARCHAR,FREQUENCY_SCALE)UPDATE RFM SET Segment ='Hibernating'
WHERE Recency_Scale LIKE '[1-2]%' AND Frequency_Scale LIKE '[1-2]%'
UPDATE RFM SET Segment ='At Risk'
WHERE Recency_Scale LIKE '[1-2]%' AND Frequency_Scale LIKE '[3-4]%'
UPDATE RFM SET Segment ='Can''t loose'
WHERE Recency_Scale LIKE '[1-2]%' AND Frequency_Scale LIKE '[5]%'
UPDATE RFM SET Segment ='About to sleep'
WHERE Recency_Scale LIKE '[3]%' AND Frequency_Scale LIKE '[1-2]%'
UPDATE RFM SET Segment ='Need attention'
WHERE Recency_Scale LIKE '[3]%' AND Frequency_Scale LIKE '[3]%'
UPDATE RFM SET Segment ='Loyal Customers'
WHERE Recency_Scale LIKE '[3-4]%' AND Frequency_Scale LIKE '[4-5]%'
UPDATE RFM SET Segment ='Promising'
WHERE Recency_Scale LIKE '[4]%' AND Frequency_Scale LIKE '[1]%'
UPDATE RFM SET Segment ='New Customers'
WHERE Recency_Scale LIKE '[5]%' AND Frequency_Scale LIKE '[1]%'
UPDATE RFM SET Segment ='Potential Loyalist'
WHERE Recency_Scale LIKE '[4-5]%' AND Frequency_Scale LIKE '[2-3]%'
UPDATE RFM SET Segment ='Champion'
WHERE Recency_Scale LIKE '[5]%' AND Frequency_Scale LIKE '[4-5]%'

SELECT * FROM RFM

SELECT SEGMENT,COUNT(*) COUNT_,ROUND(AVG(MONETARY),0) AVG_MONETARY FROM RFM
GROUP BY SEGMENT
ORDER BY 2 DESC